---
title: "EDA"
output: html_notebook
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = F)
knitr::opts_chunk$set(warning = F)
knitr::opts_chunk$set(message = F)
```

```{r}
packages <- c("funModeling" = F, "imager" = F, "grid" = F, "sqldf" = F, "tidyverse" = T, "lubridate" = T, "ggridges" = F)
installed <- installed.packages()
for (p in 1:length(packages)) {
  package.name <- names(packages[p])
  if (!(package.name %in% installed)) {
    install.packages(package.name)
  }
  if (packages[p] == T) {
    print(paste("Loading", package.name))
    library(package.name, character.only = T)
  }
}
```

```{r}
sensor.location = read_csv("./data/sensor location.csv")
day1 <- read_csv("./data/day1.csv")
day2 <- read_csv("./data/day2.csv")
day3 <- read_csv("./data/day3.csv")
zones <- read_csv("./data/zones.csv")
```

# Data Status

```{r}
funModeling::df_status(sensor.location)
```

```{r}
funModeling::df_status(day1)
```

```{r}
funModeling::df_status(day2)
```

```{r}
funModeling::df_status(day3)
```

```{r}
funModeling::df_status(zones)
```


# Data Cleaning

```{r}
sensor.location <-
  sensor.location %>%
  mutate(sid = as.factor(sid)) %>%
  mutate_if(is.numeric, as.integer) %>%
  mutate(px = y,
         py = max(x) - x)
```

```{r}
clean_days <- function(df) {
  df %>%
    mutate_at(vars(id, sid), as.factor) %>%
    mutate(time_of_day = seconds_to_period(time)) %>%
    return()
}
day1 <- clean_days(day1)
day2 <- clean_days(day2)
day3 <- clean_days(day3)
```

# Sensor Distribution

```{r}
floor1 <- grid::rasterGrob(imager::load.image("./floor plan/floor 1 cleaned.jpg"), width = unit(1,"npc"), height = unit(1,"npc"))
floor2 <- grid::rasterGrob(imager::load.image("./floor plan/floor 2 cleaned.jpg"), width = unit(1,"npc"), height = unit(1,"npc"))
```

```{r}
sensor.location <- sqldf::sqldf("
SELECT `sensor.location`.sid, `sensor.location`.floor, `sensor.location`.x, `sensor.location`.y, `sensor.location`.px, `sensor.location`.py, `zones`.area
FROM `sensor.location`
LEFT JOIN `zones`
ON `sensor.location`.floor = `zones`.floor
AND `sensor.location`.px >= `zones`.start_px AND `sensor.location`.px <= `zones`.end_px
AND `sensor.location`.py >= `zones`.start_py AND `sensor.location`.py <= `zones`.end_py
")
sensor.location$area[is.na(sensor.location$area)] <- "common"
```

```{r, fig.width=10, fig.height=6}
sensor.location %>%
  filter(floor == 1) %>%
  ggplot(aes(x = px, y = py)) +
  annotation_custom(floor1,
                    xmin=-0.5, xmax=29.5, ymin=-0.5, ymax=15.5) + # Shiny can handle the loading of background images
  geom_tile(aes(fill = area), alpha = 0.5) +
  scale_x_continuous(breaks = seq(0, 30, 1)) +
  scale_y_continuous(breaks = seq(0, 20, 1))
```

```{r, fig.width=10, fig.height=6}
sensor.location %>%
  filter(floor == 2) %>%
  ggplot(aes(x = px, y = py))+
  annotation_custom(floor2,
                    xmin=-0.5, xmax=29.5, ymin=-0.5, ymax=15.5) + # Shiny can handle the loading of background images
  geom_tile(aes(fill = area), alpha = 0.5) +
  scale_x_continuous(breaks = seq(0, 30, 1)) +
  scale_y_continuous(breaks = seq(0, 20, 1)) +
  coord_cartesian(xlim = c(0,30))
```

```{r}
areas.include <- c("main convention", "exhibition hall a", "exhibition hall b", "exhibition hall c", "exhibition hall d", "exhibition hall", "poster area",
                   "room 1", "room 2", "room 3", "room 4", "room 5", "room 6", "restaurant", "rest area")
```

# Day 1

```{r}
summary(day1)
```

```{r}
day1 %>% .$id %>% unique() %>% length()
```

Numer of visitors on first day: 3564.

```{r}
day1 <-
  day1 %>%
  inner_join(sensor.location, by = "sid")
```
```{r}
day1 <-
  day1 %>%
  arrange(id, time) %>%
  group_by(id) %>%
  mutate(time_stayed = lead(time) - time) %>%
  ungroup()
#day1$time_stayed[is.na(day1$time_stayed)] <- 0
```

```{r}
day1
```

```{r}
day1 %>%
  group_by(id) %>%
  summarise(start_time = min(time),
            end_time = max(time),
            duration_seconds = end_time - start_time) %>%
  mutate(duration_period = seconds_to_period(duration_seconds)) %>%
  ggplot() +
  geom_histogram(aes(x = round(duration_seconds / 60)), binwidth = 30) +
  scale_x_continuous(breaks = seq(0, 900, 60)) +
  labs(x = "Duration Stayed (Minutes)", y = "Number of Visitors", title = "Distribution of Duration Stayed on Day 1")
```

```{r}
day1 %>%
  filter(area %in% areas.include) %>%
  group_by(id) %>%
  summarise(areas_visited = length(unique(area))) %>%
  ggplot() +
  geom_histogram(aes(x=areas_visited), binwidth = 1) +
  scale_x_continuous(breaks = seq(1, length(areas.include), 1)) +
  labs(x = "Number of Areas Visited", y = "Visitor Count", title = "Distirbution of Number of Areas Visited on Day 1")
```

```{r}
day1 %>%
  filter(area %in% areas.include) %>%
  group_by(id, area) %>%
  summarise(time_stayed = sum(time_stayed)) %>%
  ggplot() +
  geom_boxplot(aes(x = area, y = round(time_stayed/60))) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Event Area", y = "Duration Stayed (Minutes)", title = "Duration Stayed at Each Exhibition Area for each Visitor on Day 1")
```

# Day 2

```{r}
summary(day2)
```

```{r}
day2 %>% .$id %>% unique() %>% length()
```

There are 4434 unique visitions on day 2.

```{r}
day2 <-
  day2 %>%
  inner_join(sensor.location, by = "sid")
```
```{r}
day2 <-
  day2 %>%
  arrange(id, time) %>%
  group_by(id) %>%
  mutate(time_stayed = lead(time) - time) %>%
  ungroup()
#day1$time_stayed[is.na(day1$time_stayed)] <- 0
```

```{r}
day2 %>%
  group_by(id) %>%
  summarise(start_time = min(time),
            end_time = max(time),
            duration_seconds = end_time - start_time) %>%
  mutate(duration_period = seconds_to_period(duration_seconds)) %>%
  ggplot() +
  geom_histogram(aes(x = round(duration_seconds / 60)), binwidth = 30) +
  scale_x_continuous(breaks = seq(0, 900, 60)) +
  labs(x = "Duration Stayed (Minutes)", y = "Number of Visitors", title = "Distribution of Duration Stayed on Day 2")
```

```{r}
day2 %>%
  filter(area %in% areas.include) %>%
  group_by(id) %>%
  summarise(areas_visited = length(unique(area))) %>%
  ggplot() +
  geom_histogram(aes(x=areas_visited), binwidth = 1) +
  scale_x_continuous(breaks = seq(1, length(areas.include), 1))
```

```{r}
day2 %>%
  filter(area %in% areas.include) %>%
  group_by(id, area) %>%
  summarise(time_stayed = sum(time_stayed)) %>%
  ggplot() +
  geom_boxplot(aes(x = area, y = round(time_stayed/60))) +
  theme(axis.text.x = element_text(angle = 90))
```

# Day 3

```{r}
summary(day3)
```

```{r}
day3 %>% .$id %>% unique() %>% length()
```

The number of unique visitors on day 3 is 2930.

```{r}
day3 <-
  day3 %>%
  inner_join(sensor.location, by = "sid")
```
```{r}
day3 <-
  day3 %>%
  arrange(id, time) %>%
  group_by(id) %>%
  mutate(time_stayed = lead(time) - time) %>%
  ungroup()
#day1$time_stayed[is.na(day1$time_stayed)] <- 0
```

```{r}
day3 %>%
  group_by(id) %>%
  summarise(start_time = min(time),
            end_time = max(time),
            duration_seconds = end_time - start_time) %>%
  mutate(duration_period = seconds_to_period(duration_seconds)) %>%
  ggplot() +
  geom_histogram(aes(x = round(duration_seconds / 60)), binwidth = 30) +
  scale_x_continuous(breaks = seq(0, 900, 60)) +
  labs(x = "Duration Stayed (Minutes)", y = "Number of Visitors", title = "Distribution of Duration Stayed on Day 3")
```

```{r}
day3 %>%
  filter(area %in% areas.include) %>%
  group_by(id) %>%
  summarise(areas_visited = length(unique(area))) %>%
  ggplot() +
  geom_histogram(aes(x=areas_visited), binwidth = 1) +
  scale_x_continuous(breaks = seq(1, length(areas.include), 1))
```

```{r}
day3 %>%
  filter(area %in% areas.include) %>%
  group_by(id, area) %>%
  summarise(time_stayed = sum(time_stayed)) %>%
  ggplot() +
  geom_boxplot(aes(x = area, y = round(time_stayed/60))) +
  theme(axis.text.x = element_text(angle = 90))
```

# Area Population over Time

```{r}
simplify_day <- function(df) {
  df %>%
  select(id, time, area) %>%
  group_by(id) %>%
  mutate(previous_area = lag(area),
         area_change = ifelse(!is.na(previous_area) & area != previous_area, 1, 0),
         area_index = cumsum(area_change)) %>%
  ungroup() %>%
  arrange(id, time) %>%
  group_by(id, area_index, area) %>%
  summarise(time = min(time)) %>%
  ungroup() %>%
  arrange(id, time) %>%
  group_by(id) %>%
  mutate(time_end = lead(time) - 1) %>%
  mutate(time_end = ifelse(is.na(time_end), time + 60, time_end),
         time_stayed = time_end - time) %>%
  ungroup()
}
```

```{r}
day1.simplified <- simplify_day(day1)
day2.simplified <- simplify_day(day2)
day3.simplified <- simplify_day(day3)
```

```{r}
calculate_area_population <- function(simplified.df) {
  timeslots <- data.frame(start_time = seq(as.integer(min(simplified.df$time)/60) * 60, as.integer(max(simplified.df$time_end)/60) * 60, 60))
  timeslots$end_time <- lead(timeslots$start_time) - 1
  timeslots$join <- 1
  timeslots <-
    data.frame(area = areas.include, join = 1) %>%
    left_join(timeslots, by = "join") %>%
    select(area, start_time, end_time)
  sqldf::sqldf("
    SELECT `timeslots`.area, `timeslots`.start_time, `timeslots`.end_time, `simplified.df`.id
    FROM `timeslots` LEFT JOIN `simplified.df`
    ON `timeslots`.area = `simplified.df`.area
    AND NOT (`timeslots`.start_time > `simplified.df`.time_end OR `timeslots`.end_time < `simplified.df`.time)
  ") %>%
  drop_na() %>%
  group_by(area, start_time, end_time) %>%
  summarise(visitor_count = length(unique(id))) %>%
  return()
}
```

```{r}
day1.area <- calculate_area_population(day1.simplified)
day2.area <- calculate_area_population(day2.simplified)
day3.area <- calculate_area_population(day3.simplified)
```

```{r, eval=FALSE}
write_csv(day1.area, "./data/day1_area.csv")
write_csv(day2.area, "./data/day2_area.csv")
write_csv(day3.area, "./data/day3_area.csv")
```

```{r}
day1.area %>%
  mutate(visitor_count_index = log10(visitor_count)) %>%
  ggplot(aes(x = start_time, y = as.factor(area))) +
  ggridges::geom_ridgeline(aes(height = visitor_count_index, group = as.factor(area))) +
  labs(x = "Time in Seconds", y ="Area", title = "Area Visitor over Time on Day 1")
```

```{r}
day2.area %>%
  mutate(visitor_count_index = log10(visitor_count)) %>%
  ggplot(aes(x = start_time, y = as.factor(area))) +
  ggridges::geom_ridgeline(aes(height = visitor_count_index, group = as.factor(area))) +
  labs(x = "Time in Seconds", y ="Area", title = "Area Visitor over Time on Day 2")
```

```{r}
day3.area %>%
  mutate(visitor_count_index = log10(visitor_count)) %>%
  ggplot(aes(x = start_time, y = as.factor(area))) +
  ggridges::geom_ridgeline(aes(height = visitor_count_index, group = as.factor(area))) +
  labs(x = "Time in Seconds", y ="Area", title = "Area Visitor over Time on Day 2")
```


